name: 'Cancel Workflow Runs'
description: 'Cancel Workflow Runs - duplicates, failed, named in order to limit job usage,'
author: 'potiuk'
inputs:
  token:
    description: The GITHUB_TOKEN secret of the repository
    required: true
  sourceRunId:
    description: |
      The run that triggered the action. It should be set to
      `$\{\{ github.event.workflow_run.id` variable \}\}` if used in `workflow_run` triggered run if
      you want to act on source workflow rather than the triggered run.
    required: false
  notifyPRCancel:
    description: |
      Boolean. If set to true, it notifies the cancelled PRs with a comment containing reason why
      they are being cancelled.
    required: false
  notifyPRCancelMessage:
    description: |
      Optional cancel message to use instead of the default one when notifyPRCancel is true.
    required: false
  notifyPRMessageStart:
    description: |
      Only for workflow_run events triggered by the PRs. If not empty, it notifies those PRs with the
      message specified at the start of the workflow - adding the link to the triggered workflow_run.
    required: false
  cancelMode:
    description: |
      The mode of cancel. One of:
          * `duplicates`  - cancels past, duplicate runs from the same repo/branch as local run or
                            sourceId workflow. This is the default mode when cancelMode is not specified.
          * `self`        - cancels self run - either own run if sourceRunId is not set, or
                            the source run that triggered the `workflow_run'
          * `failedJobs`  - cancels all runs that failed in jobs matching one of the regexps
          * `namedJobs`   - cancels runs where names of some jobs match some of regexps
    required: false
  jobNameRegexps:
    description: |
      Array of job name regexps (JSON-encoded string). Used by `failedJobs` and `namedJobs` cancel modes
      to match job names of workflow runs.
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'play'
  color: 'blue'
